### ISSUE TITLE
modif pour que les commentaires apparaissent sur l'export tei 

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/dictionnaire#113]
NOTE : c'est pas concluant. En fait, j'ai modifié export_tei.html et routes.py en ajoutant un paramètre commentaire dans le render_template pour éviter des erreurs de nom. Mais du coup, j'ai ça qui s'affiche pour les commentaires  : [<Commentaire 1>, <Commentaire 2>]. 
Voilà, je suppose que c'est une piste donc je push quand même au cas où l'une de vous aurait une illumination...

**Comment by aimelle** [comment]
C'est bon ça marche 👌 c'est la façon dont t'appelais les commentaires qui marchait pas ; je fais une PR.

**Comment by lafrering** [comment]
Waaa, merci ! Je déteste quand c'est juste une erreur de nom...
