### ISSUE TITLE
Modèle de base de données

### ISSUE THREAD

**Issue by AlyxTaj** [Chartes-TNAH/dictionnaire#13]
J'ai importé un fichier **datamodel.sql** modifié d'après celui de gazetteer.

J'ai remplacé et retravaillé les tables :
- `gazetteer` par `sortiaria` 
- `place` par `mot`
- `user` par `utilisateur`
- `authorship` par `auteur`
- supprimé la table `variante` et créé la table `commentaire`

J'ai gardé une seule ligne d'insertion dans la table `mot` avec le mot "alchimiste" tiré du wiktionnaire : 
[https://fr.wiktionary.org/wiki/Thésaurus:magie/français](url)

J'ai pour l'instant laissé un élément `mot_commentaire` dans la table `mot`, mais je ne vois pas encore clairement comment faire le lien entre une entrée du dictionnaire et un commentaire.
Je crois qu'il vaut mieux ne pas avoir ce `mot_commentaire` et plutôt se servir uniquement de la table `commentaire` pour lier le terme et le commentaire ; de la table `auteur` pour lier l'utilisateur et les commentaires qu'il·elle a fait sur les différents mots.

**Comment by lafrering** [comment]
Ça m'a l'air pas mal tout ça. 
Par contre, il serait judicieux de garder `user`. Peut-être aussi `authorship`, à toi de voir.
Et, il faudrait rajouter une clé étrangère `commentaire_id` dans la table auteur, pour faire le lien. 
Il y a une faute de frappe dans ```DROP SCHEMA IF EXISTS `sortiara` ;```

Et puis, qu'est-ce que c'est que  
```
INDEX `fk_auteur_1_idx` (`auteur_mot_id` ASC),
INDEX `fk_auteur_2_idx` (`auteur_utilisateur_id` ASC),
``` 
????? auteur_1 ? auteur_2 ?

**Comment by AlyxTaj** [comment]
J'ai ajouté sur la branch `database` un fichier db_sortiaria.mwb, qui est une version de la base de données réalisée sur mysql workbench. 
Cette version est sans doute encore incomplète. 
Le mot-clé "commentaire" a été remplacé par "comment", mais sans doute faudrait-il conserver commentaire pour éviter les problèmes avec les fichiers qui ont déjà incorporé les infos "commentaire".

**Comment by AlyxTaj** [comment]
Comment rétabli en commentaire dans le fichier mwb
