### ISSUE TITLE
Sortie en TEI sur une URL

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/dictionnaire#18]
Dans nos consignes, il y a une sortie en TEI à prévoir ("On proposera une sortie TEI simple à afficher sur une URL précise ( /entree/motdudictionnaire/xml-tei par exemple").
Est-ce qu'il s'agit de créer un bouton "exporter en xml-tei" sur la page d'un mot ? Ce bouton serait un lien qui pointerait vers une URL de type /demonologie.xml. Ce lien permettrait le téléchargement d'un fichier tei comme ceci : 
```
<mot>Démonologie</mot>
<definition>blablabla</definition>
<commentaire>
       <auteur>Untel</auteur>
       <texte>commentaire</texte>
 </commentaire>
```
Bien entendu mon exemple n'est pas du tout conforme.
En tout cas, c'est ainsi que je comprends la consigne. Qu'en est-il @PonteIneptique ?

**Comment by PonteIneptique** [comment]
Tout à fait.

**Comment by AlyxTaj** [comment]
Quand j'en ai parlé avec Clérice, c'était bien ça !
