### ISSUE TITLE
Erreur "access denied" 

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/dictionnaire#57]
Bonjour @PonteIneptique 
Quand nous lançons l'application, nous obtenons cette erreur :
`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'sortiaria_user'@'localhost' (using password: YES)")`

Apparemment, c'est un problème dans la base de données mais nous ne comprenons d'où pourrait venir l'erreur. Nous sommes quelque peu désespérées...

**Comment by aimelle** [comment]
Du coup je le mets là : au delà des quelques erreurs qu'il y avait dans datamodel.sql (et le fait qu'on est vraiment des quiches et que le dossier templateS n'avait pas de s) ce qui ne fonctionnait pas c'est qu'il faut prendre son terminal et dedans entrer la commande : 

`mysql -uroot -p < datamodel.sql`

ensuite ça vous demande votre mot de passe root de mysql et normalement, quand on exécute run.py LA PAGE S'AFFICHE après le contenu non et on a encore plein de trucs à régler mais c'est déjà ça.

**Comment by lafrering** [comment]
Mais qu'est-ce que c'est BEAU ! Merci @aimelle
