### ISSUE TITLE
tentative de suppression d'un mot

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/dictionnaire#98]
j'ai modifié le donnees.py et routes.py mais je push tout ça pour qu'Armâne, qui fait le template, puisse tester

**Comment by aimelle** [comment]
Juste une remarque (là c'est les premiers tests obv) mais quand on supprime un mot il faut que ça supprime avec tous les commentaires associés (et pour le moment on fait …………… rien avec la table Authorship mais en vrai j'imagine que ça devrait ptêt aussi avec un impact là-dessus ?)
